---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache-prod
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: apache
      version: 9.2.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 2
    service:
      type: ClusterIP
